version: '3.5'
services:
  dnsmasq:
    container_name: dnsmasq
    image: strm/dnsmasq
    restart: always
    ports:
      - "${LOCAL_IP}:53:53/udp"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: ["--address=/nintendowifi.net/${LOCAL_IP}"]
  pkmn-server:
    container_name: pkmn-server
    build:
      dockerfile: ./pkmn-server/Dockerfile
      args:
        - ADMIN_USERNAME=D4w2q3UuD8jNEa9QLm2BCHc5
        - ADMIN_PASSWORD=@u4KgEfpsQx4KyCfYw3MjhQZ9
    volumes:
      - ./YDQJ:/var/www/dwc_network_server_emulator/dlc/YDQJ
      - ./YDQE:/var/www/dwc_network_server_emulator/dlc/YDQE
      - ./YDQP:/var/www/dwc_network_server_emulator/dlc/YDQP
    ports:
      - "${LOCAL_IP}:80:80/tcp"
      - "${LOCAL_IP}:443:443/tcp"
